import os
import json
from datetime import datetime

class ReportGenerator:
    def __init__(self, output_dir="reports"):
        self.output_dir = output_dir
        if not os.path.exists(output_dir):
            os.makedirs(output_dir)

    def generate(self, results, target):
        """Generates a comprehensive HTML report"""
        timestamp = datetime.now().strftime("%Y-%m-%d_%H-%M-%S")
        filename = f"FORENSIX_REPORT_{timestamp}.html"
        filepath = os.path.join(self.output_dir, filename)

        # Calculate Stats
        total_files = len(results)
        threats = sum(1 for r in results if r.get('findings') or r.get('entropy', 0) > 7.5)
        
        # HTML Content
        html = f"""
        <!DOCTYPE html>
        <html>
        <head>
            <title>FORENSIX SENTINEL REPORT</title>
            <style>
                body {{ font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; background: #1a1a1a; color: #e0e0e0; margin: 0; padding: 20px; }}
                .header {{ background: #0d0d0d; padding: 20px; border-bottom: 3px solid #00ff99; margin-bottom: 30px; }}
                h1 {{ color: #00ff99; margin: 0; }}
                .stats {{ display: flex; gap: 20px; margin-bottom: 30px; }}
                .card {{ background: #2d2d2d; padding: 20px; border-radius: 8px; flex: 1; text-align: center; }}
                .card h2 {{ font-size: 3em; margin: 0; color: #fff; }}
                .card p {{ margin: 0; color: #aaa; text-transform: uppercase; }}
                table {{ width: 100%; border-collapse: collapse; background: #252525; box-shadow: 0 4px 6px rgba(0,0,0,0.3); }}
                th {{ text-align: left; padding: 15px; background: #333; color: #00ff99; border-bottom: 2px solid #444; }}
                td {{ padding: 12px 15px; border-bottom: 1px solid #333; }}
                tr:hover {{ background: #2a2a2a; }}
                .finding {{ color: #ff5555; font-weight: bold; background: rgba(255, 85, 85, 0.1); padding: 2px 6px; border-radius: 4px; border: 1px solid rgba(255, 85, 85, 0.3); }}
                .entropy-high {{ color: #ffcc00; }}
                .metadata {{ font-size: 0.9em; color: #888; }}
                .footer {{ margin-top: 50px; text-align: center; color: #555; font-size: 0.8em; }}
            </style>
        </head>
        <body>
            <div class="header">
                <h1>🐉 FORENSIX SENTINEL</h1>
                <p>Target: {target} | Scan Date: {datetime.now()}</p>
            </div>

            <div class="stats">
                <div class="card">
                    <h2>{total_files}</h2>
                    <p>Files Analyzed</p>
                </div>
                <div class="card" style="border: 1px solid #ff5555">
                    <h2 style="color: #ff5555">{threats}</h2>
                    <p>Threats & Findings</p>
                </div>
                <div class="card">
                    <h2>{len([r for r in results if 'archive' in r['type']])}</h2>
                    <p>Archives Extracted</p>
                </div>
            </div>

            <h2>🔎 Detailed Findings</h2>
            <table>
                <thead>
                    <tr>
                        <th>Filename</th>
                        <th>Type</th>
                        <th>Entropy</th>
                        <th>Intelligence Findings</th>
                        <th>Integrity (SHA256)</th>
                    </tr>
                </thead>
                <tbody>
        """

        for r in results:
            findings_html = ""
            if r.get('findings'):
                findings_html = "<br>".join([f"<span class='finding'>{f}</span>" for f in r['findings']])
            elif r.get('entropy', 0) > 7.5:
                findings_html = "<span class='entropy-high'>⚠️ High Entropy (Encrypted?)</span>"
            elif r.get('strings_count', 0) > 0:
                 findings_html = f"<span style='color:#00ccff'>Parsed {r['strings_count']} strings</span>"
            else:
                findings_html = "<span style='color:#555'>Clean</span>"

            sha_short = r['hashes'].get('sha256', '')[:12] + "..."

            html += f"""
                    <tr>
                        <td><strong>{r['filename']}</strong><br><span class="metadata">{r['size_bytes']} bytes</span></td>
                        <td>{r['type']}</td>
                        <td class="{ 'entropy-high' if r.get('entropy', 0) > 7.5 else '' }">{r.get('entropy', 0)}</td>
                        <td>{findings_html}</td>
                        <td style="font-family: monospace; color: #888">{sha_short}</td>
                    </tr>
            """

        html += """
                </tbody>
            </table>
            
            <div class="footer">
                GENERATED BY FORENSIX SENTINEL v2.0 - BEAST MODE
                <br>
                CONFIDENTIAL FORENSIC REPORT
            </div>
        </body>
        </html>
        """

        with open(filepath, 'w', encoding='utf-8') as f:
            f.write(html)
            
        return filepath
